export const Categories = [
  {
    id: 1,
    title: "Amp",
    slug: "amp",
    pluralTitle: "Amps",
    order: 1,
    sort: 0,
  },
  {
    id: 5,
    title: "Amps Collection",
    slug: "amp-collection",
    pluralTitle: "Amps Collection",
    order: 2,
    sort: -1,
  },

  {
    id: 3,
    title: "Pedal",
    slug: "pedal",
    pluralTitle: "Pedals",
    order: 3,
    sort: 1,
  },
  {
    id: 7,
    title: "Pedal Collection",
    slug: "pedal-collection",
    pluralTitle: "Pedals Collection",
    order: 4,
    sort: -1,
  },
  {
    id: 2,
    title: "Full Rig",
    slug: "full-rig",
    pluralTitle: "Full Rigs",
    order: 5,
    sort: 2,
  },
  {
    id: 6,
    title: "Full Rig Collection",
    slug: "fullrig-collection",
    pluralTitle: "Full Rigs Collection",
    order: 6,
    sort: -1,
  },
  {
    id: 4,
    title: "IR",
    slug: "ir",
    pluralTitle: "IRs",
    order: 7,
    sort: 4,
    active: false,
  },
  {
    id: 8,
    title: "IR Collection",
    slug: "ir-collection",
    pluralTitle: "IRs Collection",
    order: 8,
    sort: -1,
    active: false,
  },
  {
    id: 9,
    title: "Outboard",
    slug: "outboard",
    pluralTitle: "Outboards",
    order: 9,
    sort: 3,
  },
  {
    id: 10,
    title: "Outboard Collection",
    slug: "outboard-collection",
    pluralTitle: "Outboards Collection",
    order: 10,
    sort: -1,
  },
];
